### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by kingola1** [trananhtuat/react-movie#2]
The Swiper Is Causing the images not to be shown

**Comment by safarsafarov** [comment]
> The Swiper Is Causing the images not to be shown

change the Swiper to the Router

**Comment by kingola1** [comment]
Okay

**Comment by kingola1** [comment]
I actually fixed it by downgrading react version to 17 it was react 18 that was terminating something's

**Comment by sudiptapradhan** [comment]
> I actually fixed it by downgrading react version to 17 it was react 18 that was terminating something's

any other solution apart from this?

**Comment by sudiptapradhan** [comment]
> > The Swiper Is Causing the images not to be shown
> 
> change the Swiper to the Router

can you please send your HeroSlide.jsx code
